name: 'qntproj'
version: '1.0.0'

profile: 'qntproj'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  qntproj:
    staging:
      +materialized: view
    ods:
      +materialized: view
    mart:
      +materialized: table
